### ISSUE TITLE
inference resume fails

### ISSUE THREAD

**Issue by jarheadjoe** [KwanWaiChung/M4LE#4]
![image](https://github.com/KwanWaiChung/M4LE/assets/21330284/37321c1c-4117-458e-9963-0ce749a886e9)

**Comment by KwanWaiChung** [comment]
Thanks for reporting a bug. We have fixed the bug in the latest commit [e51e404](https://github.com/KwanWaiChung/M4LE/commit/e51e404f5798eae05ccfa01e7f2ba5ce19fd7196).
