### ISSUE TITLE
will you report the results used for plotting Figure 3 ?

### ISSUE THREAD

**Issue by jarheadjoe** [KwanWaiChung/M4LE#6]
Figure 2 is plotted by length_bucket(word count), Figure 3 is plotted by tokens. Am I understanding this correctly? Then the data plotted in Figure 3 is not disclosed in the text, can it be provided？

**Comment by KwanWaiChung** [comment]
Both plots are generated based on word counts referred as space-separated words in the text. In the paper, we use "words" and "tokens" interchangeably. To avoid ambiguity, we will universally adopt the term "word" throughout the paper in the next update.

Regarding Figure 3 data for plotting, it can be found in Table 4, 5, and 6 respectively. If you have any further questions, please feel free to ask. Thank you.
